### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by alekxeyuk** [qwertyadrian/vk-music-downloader#1]
![image](https://user-images.githubusercontent.com/9300326/47786095-64a10400-dd56-11e8-93b0-414c3129c094.png)
Не работает
[Мой профиль](https://vk.com/audios216681443)

**Comment by qwertyadrian** [comment]
@alekxeyuk Опа...

**Comment by qwertyadrian** [comment]
Сейчас посмотрим.

**Comment by qwertyadrian** [comment]
Попробуйте воспользоваться новой версией программы: [`VkMusic Downloader 0.5.0`](https://github.com/qwertyadrian/vk-music-downloader/releases/tag/v0.5.0)
