### ISSUE TITLE
Множество неприятных багов\фишек

### ISSUE THREAD

**Issue by Crysstalka** [qwertyadrian/vk-music-downloader#2]
В последнем обновлении появился противный мелкий баг: в случае, если аудиозаписи пользователя закрыты, то программа вылетает. Также нет никакой инструкции по скачиванию и/или больших кнопок, как в предыдущих версиях.

**Comment by qwertyadrian** [comment]
Аудиозаписи считаются закрытыми, если к ним никто не может получить доступ кроме владельца аккаунта, а программа в этом случае сообщает об этом. Также при любой возникшей ошибке программа выводит ее на экран, а не просто вылетает.

**Comment by Crysstalka** [comment]
Но у меня вылетает программа, а не выдаёт ошибку. Такое наблюдал только в последней версии.

**Comment by qwertyadrian** [comment]
То есть она просто закрывается?

**Comment by Crysstalka** [comment]
Да.

**Comment by Crysstalka** [comment]
Можете проверить на моих аудиозаписях, они закрыты.

**Comment by qwertyadrian** [comment]
Если они закрыты, то программа даже не сможет получить список аудиозаписей.

**Comment by Crysstalka** [comment]
Но почему она вылетает?

**Comment by qwertyadrian** [comment]
Попробуйте данную версию программы: [VkMusic Downloader 0.5.1](https://github.com/qwertyadrian/vk-music-downloader/releases/tag/v0.5.1)
