### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Lavmint** [qwertyadrian/vk-music-downloader#4]
При получение альбомов
`albums = [vk_audio.get_albums(id['id'])]`
выбрасывает ошибку:
```
invalid literal for int() with base 10: '1,729'
<class 'ValueError'>
```
Если закомментировать альбомы, то все работает как надо

Тестировалось для загрузки музыки [этого](https://vk.com/id215185126) мсье
OS X Mojave 10.14
Python 3.7.1
vk_api 11.3.0
bs4 0.0.1

**Comment by qwertyadrian** [comment]
Ошибка возникает в результате получения неверных данных в строке `id = api_vk.users.get(user_ids=user_id)[0]`, а именно получено неверное ID пользователя. Должно было быть значение `215185126`, а у вас вышло `1,729`.

Возможно, проблема кроется в работе библиотеки vk_api. Попробуйте установить более старую версию библиотеки, например 9.3.2

**Comment by Lavmint** [comment]
Спасибо за ответ, проверять я это конечно же не буду )
Предлагаю указать в `requirements.txt` рекомендуемую версию vk_api
P.S. крутая прога ❤
