### ISSUE TITLE
Ошибка[3] Unknown method passed

### ISSUE THREAD

**Issue by huuga** [qwertyadrian/vk-music-downloader#8]
Привет! Программа выдает такую ошибку.  Логин пароль и ссылку на свой профиль прописал. Аккаунт открытый. Когда нажиму. кнопку получить аудиозаписи, выдает такую ошибку. ОС Windows. Запускал через PyCharm. В чем может быть дело?

**Comment by qwertyadrian** [comment]
Привет. Похоже, что вами использовалась устаревшая версия программы. Актуальная версия была в другой ветке, которая теперь объединена с [основной](https://github.com/qwertyadrian/vk-music-downloader/tree/master). Обновите локальный репозиторий и повторите попытку.
